//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BudgetMunchiesAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Developer
    {
        public Developer()
        {
            this.DeveloperTokens = new HashSet<DeveloperToken>();
        }
    
        public string userName { get; set; }
        public string password { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string apiKey { get; set; }
        public string email { get; set; }
    
        public virtual ICollection<DeveloperToken> DeveloperTokens { get; set; }
    }
}
